# Generated by Django 5.0.4 on 2024-04-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date_refusal',
            field=models.DateTimeField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='date_restoration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата восстановления'),
        ),
    ]
